// Bhutan administrative hierarchy: Dzongkhag > Gewog/Thromde > Chiwog/Village.
// Source: Election Commission of Bhutan — Delimitation of Parliamentary and Local
// Government Constituencies Order (NameChangeOrderEnglish.pdf, 2013-04-10).
// 20 dzongkhags, 207 units, 1051 leaf records. Names transcribed as printed.

export type BhutanTree = Record<string, Record<string, string[]>>;

export const BHUTAN_ADMIN: BhutanTree = {
  "Bumthang": {
    "Chhoekhor": ["Nangsiphel_Zangling_Zhabjethang", "Dhur_ Lusibee", "Kharsa_Thangbi", "Dawathang_Dorjibi_Kashingtsawa", "Pedtsheling_Tamzhing"],
    "Tang": ["Tandingang", "Khangrab", "Kidzom_Nyimalung", "Dazur", "Bepzur_Kuenzangdrag"],
    "Chhumig": ["Gyaltsa", "Domkhar", "Phurjoen", "Zung-Ngae", "Choongphel"],
    "Ura": ["Beteng_Pangkhar_Somthrang", "Tangsibi", "Shing-Nyer", "Ura-Dozhi", "Shingkhar"],
  },
  "Chhukha": {
    "Bjagchhog": ["Bjagchhog", "Tsimalakha_Tsimasham", "Mebisa", "Tashi Gatshel", "Wangkha"],
    "Bongo": ["Togtokha_Togtogongm", "Choongkha_Chhasilakha", "Gedu_Miritsemo", "Ketogkha", "Bongo_Phasooma", "Baeyuel Kunzang"],
    "Chapchha": ["Pagga", "Tshamdrag", "Gangkha_Shel-Yuel", "Dokharchhu_Rimtekha", "Lang Nyelsa", "Bunakha"],
    "Darla": ["Tagp-Thang-Bu", "Nyimgang_Tabji", "Gengu_Yagang", "Samarchen_Sinchula", "Gamanang_Kalzang-ri"],
    "Getana": ["Sharphu", "Darga_Tshebji", "Tashigang", "Janamo_Phootsha", "Bachhu_Getana", "Chiyuel_Getag"],
    "Doongna": ["Babana_Papaling", "Chhulakha_Mangdokha", "Doongna_Pagsel-Lakha", "Drukdingsa_Khori", "Damchhekha_Uezhi"],
    "Geling": ["Gelingkha_Tsanglingna", "Dagpa_Sorchen", "Geling_Geygoen", "Kamji_Na-Yekha", "Dilibkha_Lamjokha"],
    "Loggchina": ["Chagdokha_Damchhekha", "Dolepchen_Bjagchhu", "Aamleg_Dofam", "Dzedokha"],
    "Maedtabkha": ["Mongna_Lha-sarp", "Pangu", "Jozhingkha_Maedtab-Toed"],
    "Phuentshogling": ["Maedtab-Maed", "Uekha", "Gumina_Tenchhukha", "Lingdaen", "Pachhu", "Dophuchen_Wangdue Gatshel", "Deling_Marpji", "Chong-Geykha_Dophulakha"],
    "Samphelling": ["Pekarling_Rigzinling", "Sengyegang_Tsho-Chhoongna", "Khenpaithang_Sonamthang", "Gongboogang_Pangna", "Pedtshel-Nang"],
  },
  "Dagana": {
    "Drukjeygang": ["Pangna_Patala", "Thangna", "Boodepang_Pangna", "Ambithang_Pangserpo", "Pangserpo"],
    "Gozhi": ["Dogaag", "Baleggang", "Gozhi-Maed", "Gozhi-Toed", "Gozhi"],
    "Karna": ["Lhaling", "Poongzhi", "Dalithang_ Gangyab_Khagochen", "Bartsha_Namgyalgang", "Jurugang"],
    "Khebisa": ["Pogtog", "Pagser", "Akhochen", "Thongmgang", "Gibsa"],
    "Largyab": ["Baloong", "Thasa", "Kompa"],
    "Tseza": ["Barna", "Sidpa", "Pel-Ling", "Tashigang", "Samaed", "Karling Dzingkha", "Tsanglegkha"],
    "Tsangkha": ["Gelegchhu", "Tsangkha", "Zinchila", "Goongpa-Soomchu", "Paateykha"],
    "Karmaling": ["Labtsakha", "Omchhu", "Senchumthang", "Karmaling", "Jemathang"],
    "Dorona": ["Maamedthang", "Nyimtola", "Dorona Chhewa", "Dorona Chhoongwa"],
    "Gesarling": ["Tshalamji", "Tajoog", "Samtengang", "Gesarling"],
    "Lhamoi Dzingkha": ["Puensoomgang", "Tashithang", "Tsham-Zhi-Gosa", "Lhamoi Dzingkha", "Chongsamling", "Loongsilsa", "Kuendrelthang"],
    "Nichula": ["Dramze-Kesa", "Yarphelling", "Damchhunang", "Dangreybu", "Gangtogkha"],
    "Tashiding": ["Shamdolay", "Tashiding", "Namchagla", "Norbuling", "Gangyab"],
    "Tsenda-Gang": ["Tsenda-Gang", "Gangzur-Maed", "Gangzur-Toed", "Norbu-Zhingkha", "Samarchhu"],
  },
  "Gasa": {
    "Khamaed": ["Gayza_Zomina", "Jabisa", "Damji", "Barsha_Panikong", "Khailog_Tarshingthang"],
    "Lunana": ["Thangza_Toenchoe", "Tshozhong", "Lhedi", "Shang_Threlga_Wachey", "Raminang_Uesana"],
    "Khatoed": ["Chhogley_Phulakha", "Mani", "Baychhu_Tshedpgang", "Tsheringkha", "Rimi"],
    "Laya": ["Gyalza_Loong-Go", "Neyloog", "Toedkor", "Pazhi", "Chongra_Loobchag"],
  },
  "Haa": {
    "Bji": ["Gensa_Tokey", "Chenpa_Geychhukha", "Tsenka_ Taloong"],
    "Kar-tshog": ["Choompa_Jamgoen", "Yangthang", "Bali_Mombitshokha", "Kargoen_Hatam", "Dragding_Karjena", "Ingo_Pharikha", "Wangtsa"],
    "Uesu": ["Betso_ Doomchhog", "Geyruna_Karnag", "Pajekha_Sangkiri", "Kipri_Tagchhu", "Tshaphel_Tsiloongkha"],
    "Gakiling": ["Dorithasa_Kowkha_Yangtse", "Rangtse_Ta-Nga_Yokha", "Sai-dzong_Thangdokha", "Phootsena_Ngatse", "Fentena_Sertena"],
    "Samar": ["Dorikha_Langjogang", "Langpa_Norbugang", "Balamnang", "Jenkanang_Pudunang", "Shar-ri"],
    "Sangbay": ["Mochhu", "Nakha_Tashigang", "Anakha_Shepji", "Shema_Yaba", "Sangbay Ama"],
  },
  "Lhuentse": {
    "Gangzur": ["Ney", "Thrima_Shawa_Zhamling", "Kyidloong_Somshing", "Nyimzhong_Tongling", "Jang_Ngar"],
    "Khoma": ["Rolmoteng _Tsang-Ngo", "Pangkhar", "Gangla_Kholma", "Berpa_Khoma", "Babtong_Dragteng"],
    "Kurtoed": ["Jasabi_Ugyenphu", "Chagdzom_Chhusa", "Tang-Roong_Wawel", "Dungkar", "Tabi"],
    "Minjey": ["Amdrangchhu_Zham", "Chusa_Legshogang", "Minjey_Wazhing", "Draag-Gong_Jalang"],
    "Jarey": ["Boo-Dur_Kupi-Nyalsa", "Yabi_Zangkhar", "Artobi_Ngang-Ngae"],
    "Maenbi": ["Ladrong", "Kharchung", "Yumchhe", "Nyaibi_Zhungkhar", "Kamdhar_Moormo", "Phagidoong", "Tagmochhu_Gorgan", "Maenjabi"],
    "Maedtsho": ["Oong-gar", "Gortshom_Tshangthrom-Maed", "Zhongmaed", "Obi_Tongthro", "Bamdhir_Yurung"],
    "Tsaenkhar": ["Go-Nyid_Wambur", "Domkhar_Umling", "Dekaling_Tshochhen", "Autsho_Chharbi", "Artobadeb_Guendrang"],
  },
  "Monggar": {
    "Balam": ["Khebishing", "Balam_Morphu", "Bahkaphai", "Jadoong_Yangbari", "Doongmanma_Selkhar"],
    "Chagsakhar": ["Yangrapoongshing", "Kharnang_Kheshingra", "Borphai_Chagsakhar", "Doongsingma_Pam", "Yetong_Jarshingpogtor"],
    "Dramedtse": ["Serkhagphu_Yengkhartshing", "Dramedtse_Shaphangma", "Ba-Ging_Shadang", "Zangkhar", "Bikhar_Thoongdari"],
    "Na-Rang": ["Khalong", "Thrinangphu", "Gomchhu", "Na-Rang_Pangthang"],
    "Ngatshang": ["Dongshoom_Pangkhang", "Ngatshang", "Thoombari_Zangdari", "Nyingala_Phanasi"],
    "Shermuhoong": ["Pelshoob", "Yadi_Yekhar", "Soenakhar_Yarab", "Jabgang_Thiling", "Muhoong_Shiling", "Gangmoong", "Malang_Serzhong"],
    "Thang-Rong": ["Changshing", "Atola", "Lingkhar", "Ngaru-Pongtang", "Bauchhoeling_Panglen"],
    "Gongdue": ["Damkhar_Weringla", "Baagla_Dengkaling", "Pikari_Yangbari", "Daagsa_Kumadzong", "Phadzong"],
    "Jurmed": ["Ngamphu_Sangkama", "Bilam_Dangkila", "Kognala_Ya-Ragla", "Moodoongkhar_Tselam"],
    "Kengkhar": ["Moogtangkhar_Tsangkhazor", "Tongla_Zi-Tsibi", "Kyidpari_Yuldari", "Neykorlog_Warongborang"],
    "Saling": ["Olokid_Tsalabi", "Phosothong_Shingchongri", "Dogtang_Mooroong", "Seng-Gor", "Saling", "Thridangbi", "Tsenzabi_Masangdaza", "Drogsar", "Kalapang_Risa"],
    "Silambi": ["Daag", "Wama", "Gyalgong", "Pang_Nagor", "Kadag_Silambi"],
    "Chhaling": ["Chhaling_Dopang", "Chulabi", "Shebchi_Yangthang", "Pangthang_Thempang", "Wangmakhar_Khalangji"],
    "Drepoong": ["Labtsa_Shing-Gar", "Boompazor_Drepoong", "Bainangri_Nyamla", "Zunglen"],
    "Monggar": ["Chhagsuzor_Tsangkhar", "Gyalpoizhing_Wangling"],
    "Tsakaling": ["Phosorong", "Kidekhar", "Wengkhar_Yagpoogang", "Themnangbi_Ketongri", "Koenbar_Tagchhu", "Tagkhambi", "Kaling_Thoomling", "Nyartsi_Tsakaling", "Drengling_Horong", "Drongtoed_Tormazhong"],
    "Tsamang": ["Ganglapong Toed", "Ganglapong Maed", "Baanjar", "Thuenmong_Tokari", "Drangmaling_Nanggor"],
  },
  "Paro": {
    "Dokar": ["Tenchhekha_Tsiphu", "Goensakha_Phuchhekha", "Mendrel_Uesuna", "Dawakha_Tshongkha", "Khamdraag_Sali"],
    "Loong-nyi": ["Naemjog", "Jieu_Woochhu", "Dzongdraag_Gadraag", "Baangdey", "Pangbisa"],
    "Nagya": ["Bemphu_Lingzhi_Nagu", "Bueltikha_Jagoen", "Rangzhin-Gang_Tshebji", "Wanakha_Zursoona", "Jazhina_Tsoen-Goen"],
    "Sharpa": ["Bara_Zhunggar", "Drugyaldingkha", "Dochhoeten_Neyphu", "Bjizhikha_Phubarna", "Chhukha_Gangjoogkha"],
    "Dopshar-ri": ["Duezhi_Jipa", "Kempa_Kuduphu", "Rinchhending_Shar-ri", "Jangsa_Jooka", "Jizhigang"],
    "Doteng": ["Phooshar", "Aa-tsho_Phunoob", "Chhubar", "Jabji_Loogchhoed"],
    "Hoongrel": ["Joogar_Pachhu", "Gaupel", "Hoongrelkha_Jangsarbu", "Loongchhungna", "Chhubjagkha", "Goenkha"],
    "Lamgong": ["Chhukha", "Tsendonang", "Jagarthang", "Ngopa_Shomo", "Gangjoog_Kyidchhu"],
    "Tsento": ["Soe_Yagsa", "Mitshig_Shana", "Chhungjey_Zamsar", "Nyamjey_Phangdo", "Nyechhu_Shar-ri"],
    "Wangchang": ["Gebtoed_Olathang_Tajoog", "Changmedthangka_Khangkhu", "Dungkar_Namkar", "Mendrel_Nakha", "Changkar_Jangteyna"],
  },
  "Pema Gatshel": {
    "Chhimoong": ["Chhiphoong", "Nyasikhar", "Loongkholom", "Chhimoong", "Pangthang_Redingla"],
    "Chongshing": ["Gooyoom_La-Nangzor", "Thongsa", "Maendi", "Chongshing_Jorphoong", "Kamri_Yomzor"],
    "Dungmaed": ["Serduwa", "La-Nyiri_Thrumchoong", "Dungmaed_Zimzor", "Woongborang", "Bangyuel"],
    "Khar": ["Khar_Yagyur", "Bongmaan", "Shinang-ri", "Khengzor_Labar", "Nagtseri_Shemshem_Tsebar"],
    "Yurung": ["Khangma", "Bangdala", "Wanglakho_Thoong-Go", "Doongsingma_Thoongkhar", "Khominang_Yangkhar"],
    "Nanong": ["Gashigkhar_Tshatshi", "Nanong", "Raling"],
    "Shumar": ["Tokarey", "Terphu_Woongchhiloo", "Chongmashing_Dagor", "Goenpoong_Shali", "Nangkor", "Bartseri", "Khothagpa_Yalang"],
    "Zobel": ["Chhoongkhar_Pangthangdaza", "Zobel", "Ngangmalang_Zorjoog", "Raysinang", "Maan_Tshelinggor"],
    "Chhoekhorling": ["Kerong", "Dizama_Shoguri", "Yargyewoong", "Chhoekhorling_Gazawong", "Arden"],
    "Dechhenling": ["Doongchhilo_Kholomri", "Doongphu_Shingchongri", "Namdagling", "Dechhenling_Goenpawoong", "Goishing_Ridzommo", "Bidoongri_Yangmalashing"],
    "Norboogang": ["Norboogang_Rinchhenzor", "Nyingshingborang", "Tshaelshingzor", "Gashari", "Maenchhu_Nganglam"],
  },
  "Punakha": {
    "Barp": ["Chagsa", "Sobsobkha_Yuwakha_Zhikha", "Usakha", "Tshogkorna", "Gamakha_Sebtokha"],
    "Guma": ["Lakhu_Tshowogm", "Dochhukha_Dzomlingthang_Ritsa", "Baymenang_Phulingsoom_Wangwakha", "Changyul_Loongsilgang_Tashijong", "Guma_Wolakha"],
    "Goenshari": ["Goomgang", "Yorbo", "Zhelngoesa", "Draagchhukha", "Sechaed-Nang"],
    "Kabisa": ["Chhoeten Nyingpo_Uesarkha", "Sirigang_Wakoo Damchhi", "Peltari", "Agonang_Zarbisa", "Heyloog_Tongzhoognang"],
    "Talog": ["Loongnangkha", "Norbugang", "Dongkokhar_Yonggu", "Talog"],
    "Toepaisa": ["Gangthramo_Labtsakha_Soelwdrangsa", "Bichhekha_Yuel Hamo", "Dochola_Maenchhuna"],
    "Chhubu": ["Damkhyi_Rinakha", "Lemjakha_Thinleygang", "Goenmkha_Mendrelgang", "Ngoe-Droob-Chhu", "Bumtakha_Tenpakha", "Bali", "Yebisa", "Jangwakha_Sewla"],
    "Dzomi": ["Goobji_Tseykakha", "Khilikhar_Loongkha", "Tanag_Uesa", "Dzomisa_Mendagang", "Bjimithang"],
    "Lingmukha": ["Lingmukha", "Dompala", "Nabchhed", "Goomkarmo", "Umtoedkha"],
    "Shelnga-Bjemi": ["Datong", "Chongzhi_Jarigang_Jazhikha", "Khubji_Tshosa", "Gangkha", "Thongbji"],
    "Toedwang": ["Kewanang_Tshachhuphu", "Tamigdamchhu_Thangbji", "Dawakha", "Jibjo_Yuesarkha", "Tse-phu_Khawakha"],
  },
  "Samdrup Jongkhar": {
    "Dewathang": ["Rikhey", "Martang", "Domphu_Dungkarchhoeling", "Bangtsho", "Chhenangri_Rishor"],
    "Gomdar": ["Broomi_Chidoongkhar", "Denchhi", "Khoyar Pangthang_Palroong", "Gomdar_Richhanglu", "Narphoong"],
    "Orong": ["Rimoong", "Jangchhubling", "Nagzor_Wooling", "Morong", "Bilam_Orong_Suzoong", "Nabar_Philooma"],
    "Phuentshogthang": ["Minjigang", "Samdrupchhoeling", "Phuentshogthang", "Baylamsharang", "Khamaedthang", "Doongkarling"],
    "Wangphu": ["Sachhilo", "Bayuel_Pangthang", "Shogshi", "Serchhenmo_Wangphu"],
    "Langchenphu": ["Benporong_Yarphu", "Rongchhuthang", "Agoorthang"],
    "Lauri": ["Jampani", "Langchenphu", "Jangsa", "Momring_Rolnang", "Gonong_Zangthig", "Tshothang", "Betseling_Doongmanma", "Lauri"],
    "Martshala": ["Chhoedoong_Kakani", "Sarjoong", "Kaeptang_Tsholingkhar", "Suzor_Tshotsalu", "Galingkhar_Wangphu", "Martshala"],
    "Pemathang": ["Uesarna_Warong", "Raling", "Pemathang", "Chirtshosa_Loongminang", "Kathoobdang_Shiling Gye"],
    "Samrang": ["Ngangtshothang Toed", "Ngangtshothang Maed", "Damsagang Toed", "Damsagang Maed", "Tshoduen"],
    "Serthig": ["Khandophu_Minjiwoong", "Drenphu", "Phagchhog_Suskar", "Dangtsho_Serthig", "Monmola_Tashithang Gyed"],
  },
  "Samtse": {
    "Duenchhukha": ["Gawaling_Karzhing", "Domchhukha_Shitakha", "Gesarling_Yomedling", "Duenchhukha_Gabji", "Biloong_Poongthra"],
    "Dophuchen": ["Aringgang_Midzomsa", "Dangreybu_Ngagang", "Manigang_Thingyersa", "Sangloong_Sengteng", "Melong-Gang_Thuloong-Gang", "Singye"],
    "Doomtoed": ["Doomtoed_Khaling", "Maedgang", "Doomtoed Chhewa", "Gebji_Kuzhuggang", "Doomtoed_Chhungwa_Jarikha"],
    "Tading": ["Norjangsa_Zochhaling", "Dangreybu_Nyindooglakha", "Khempagang_Panzhing", "Thongsa_Tobchhenthang", "Tading_Tenpaling"],
    "Norboogang": ["Lambi_Lamjosa", "Khangduzhi_Kyidsa", "Dramzegang_Maedgang", "Dawaling_ Yangphelthang"],
    "Phuentshogpelri": ["Dhamzhagsa_Tsaphel Thang", "Tashilakha_Uelgyalling", "Chhunag_Doomshinggang", "Gashingma_Ketshael-Gang_Thongjabi", "Jangchhogling_Lachhuthang", "Nyoenpaling_Tingtingma"],
    "Samtse": ["Dewathang_Lamaithang", "Sa-tshamchhu_Tshongdzom", "Damtshangma_Khandothang", "Nyimaling_Chhirlogsa", "Lingmaithang_Taserpo"],
    "Norgaygang": ["Dangreybu_Patshaling", "Miphelgang_Samphelgang", "Chongzhu_Tshachhu", "Chhu-Goo_Phendegang", "Joenpang_Linggarnang", "Khabaabgang_Noryog"],
    "Pemaling": ["Chhusilgang_Dramedsa", "Thangchhennang_Damtshangna", "Dizang-Gang _ Nakeyling", "Manigang_Tashithang", "Norgyeling_Shingdregang"],
    "Tashichhoeling": ["Tashichhoeling", "Daangling_Gangjoog", "Dewachen_Zhiwaling", "Norjangsa_Peljorling"],
    "Tendruk": ["Baepoteng_Kangdoongphu", "Miglamthang_Thagpzosa"],
    "Sang-Ngag-Chhoeling": ["Dawathang_Kuengaling", "Khengtong_Targothang", "Kachhen_Kuchhen", "Nyizergang_Tendruk", "Joenlegsa_Sang-Ngag-Chhoeling", "Dephellingmaed_Khangzangling", "Chhuchhungsa_Chhoedeling", "Dephellingtoed_Namseling", "Ngoedroobling"],
    "Namgyalchhoeling": ["Sernyagang_Tsholingkhar", "Namgyalchhoeling", "Pagshingkha_Tshachhugang", "Chhunaggang_Chhoedeling", "Gyalposhing_Sa-Tsangsa"],
    "Ugyentse": ["Nyimalung_Tharpaling", "Kardhog", "Dangreybu_Rigpailing", "Jarithang", "Dangkarling_Dechhengang"],
    "Yoeseltse": ["Zurigang_Jigmedthang", "Rinchhenphu_Samtenchhu", "Koenchhogling_Soenamkhar", "Dungkar", "Pelkithang_Rangjoongling"],
  },
  "Sarpang": {
    "Samtenling": ["Khenpagang", "Samtenling", "Samtenthang", "Dechhen Pelri", "Chhoekhorling_ Dechhen Pelri"],
    "Chhuzanggang": ["Chagsakhar", "Pangzor", "Nyimaling_Shawapong", "Thongjabi_Yueling", "Barthang"],
    "Gelegphu": ["Pelrithang Khatoed", "Pelrithang Khamaed", "Dzomlingthang", "Pemathang", "Lekidthang"],
    "Jigme Chhoeling": ["Gongtsekha", "Gongduegang", "Khamaed", "Samkhar", "Khatoed", "Chhoetenkhar"],
    "Serzhong": ["Serzhong", "Barshong", "PemaYoedling", "Tashiphu"],
    "Tareythang": ["Norbuling", "Tashichhoeling", "Yoezergang"],
    "Umling": ["Pemachhoeling", "Dorjitse", "Woongchhiloo", "Tashithang", "Daangling", "Doongmin", "Rijoog", "Gaden"],
    "Dekiling": ["Jigmeling", "Chhoekhorling", "Nubgang", "Dekiling", "Gawaithang"],
    "Chhudzom": ["Gaalegthang", "Sherabling", "Draagchhu", "Jangchhubling", "Lhayuel"],
    "Gakiling": ["Maenchhulam", "Sangkha", "Rilangthang", "Getemkha", "Gakiling"],
    "Senggey": ["Rishong", "Sangyethang", "Yarphelling", "Labtsakha"],
    "Shompangkha": ["Nyenyul", "Gomchola", "Risoomgang", "Koenchhogling", "Shompangkha", "Dargyethang"],
  },
  "Thimphu": {
    "North Thimphu Thromde": ["Dechenchhoeling_Taba", "Changgangkha", "Jumgshina_Kawajangsa", "Motithang", "Norzin"],
    "Kawang": ["Boegarna_Dodennang", "Kuzhugchen", "Chhamina_Chhokhor", "Dazhi-Zhoshuel", "Chhangdagang_Chhoekhortse_ Phajoding"],
    "Lingzhi": ["Chhuzarkha", "Khangkiyuel", "Chakphu", "Shayuel", "Gangyuel"],
    "Naro": ["Moentsiphu", "Barshong _Nango", "Pagoed", "Tagsidthang", "Zhomthang"],
    "Soe": ["Jangothang", "Damgochong", "Dotagpaithang", "Dozotoen"],
    "South Thimphu Thromde": ["Jomphu", "Chang Bangdu_Olakha", "Babesa", "Lhoongtsho_Tashigang"],
    "Chang": ["Yoeselpang", "Chang-Yokha_Debsid", "Ramtoktok_Tsangrina", "Gangchhe_Talakha"],
    "Darkarla": ["Chamgang Maed", "Chamgang Toed", "Wangdrog", "Gyaltala", "Doongdrog"],
    "Ge-nyen": ["Tsho-chekha_Zamtog", "Ge-nyenkha", "Zang-legkha", "Chizhi", "Wangbama"],
    "Maedwang": ["Tsha-loong-na", "Jiminang", "Danglo-Namsaeling", "Khasadrupchhu", "Sisinang"],
  },
  "Trashigang": {
    "Bartsham": ["Trashang", "Bainangkhar_Nangkhar", "Jamoong_Kumoong", "Dzong Thong_Menchhari", "Moogtangkhar"],
    "Bidoong": ["Khairi_Saling", "Lemphang", "Tshekhar", "Tsigtoom", "Kakaniwog"],
    "Yangnyer": ["Daliphang_Ragshigo", "Duroong_Ngambinang", "Dargyeling_Kharthoong", "Shokang_ Tegtegpa", "Kharza_Leyphu"],
    "Shongphu": ["Galing", "Chhangmi_Rangjoong", "Gongtsephangma_Yobinang", "Chaling", "Dramin_Shongphu"],
    "Kanglung": ["Pangthang_Ritsangdoong", "Maanthong", "Mertsham_ Thra-Gom", "Yonphula", "Rongthoong_Shingchhen"],
    "Samkhar": ["Chagzam_Pam", "Maelphel_Samkhar", "Khabti_Lungtenzampa"],
    "Udzorong": ["Bikhar_Domkhar", "Kapang_Yenangdrangsa", "Rangzhikhar_ Sardang", "Benshingmo_Jomtsang", "Rizor_Yerchhilo", "Chhiya", "Barkazor_Maenkhar", "Baepam"],
    "Merag": ["Merag Toed", "Gyen-go", "Merag Maed", "Khashateng", "Khiliphoo"],
    "Phongmed": ["Phimsong", "Ya-Brang", "Thong-Rong", "Phongmed", "Lem"],
    "Radhi": ["Pakaling", "Dekiling_Tsenkhar", "Tongling Pam", "Kadam", "Nagtshang_Togshingmang"],
    "Sagteng": ["Thrag Thri", "Borangmang_Borangtse", "Joenkhar_Moorbi", "Sagteng"],
    "Kangpar": ["Pusa_Tenmang", "Bedengphu_Merdag", "Threlphu"],
    "Thrimshing": ["Zordoong", "Kangpar_Lamyong", "Passaphu_Peydoong", "Thrimshing", "Doongsingma_Tsangpo", "Bongzor_Phegpari", "Ramchongma_Yemkhar", "Berdoongma_Thoongkhar"],
    "Khaling": ["Jiri_Lemi", "Barshong", "Gomchhu_Kholdoong", "Khaling", "Brekha_Merengzor", "Bayphu_Togkaphu"],
    "Lumang": ["Chhengri_Doongmanma", "Dubkhang_Lumang", "Kharphu_Kurchhilo", "Riserbu_Tsangpo", "Moochhu_Wakhar", "Tshogoenpa"],
  },
  "Trashi Yangtse": {
    "Boomdeling": ["Pangkhar_Taphel", "Ngalimang_Phanteng", "Betsamang", "Bomdhir_Wogmanang", "Gangkhardoong_Tshaleng"],
    "Jamkhar": ["Laishoom_Largyab", "Chhema_Taagchhema", "Shingkhar_Tongla", "Rijoong_Yoob", "Neydraag_Paechhu"],
    "Tongmajangsa": ["Maenchhu_Tsangdhoong", "Pang-Lhauzhing", "Changmadoong_Soggangnang", "Baagpa_Kuenzangling", "Bainangkhar_Gomkora"],
    "Yangtse": ["Bayling", "Baaney_Bimkhar", "Lichen", "Gangkhar", "Rabti"],
    "Ramjar": ["Dhomtshang_Doongmaen", "Bawoong", "Lengbartang_Woongkhar", "Bainang-Reb_Romang"],
    "Khamdang": ["Khalapangthang_Tsang-Rong", "Doongtse_Lengkhar", "Dhomtshang_Karmadzom", "Serpang_Shalli", "Nombaring_Shazam", "Khamdang_Manla"],
    "Toedtsho": ["Nangkhar_Seb", "Sertsho", "Jangphootse_Thangdoong", "Maeldoong", "Khi-Nyel_Togshing", "Chhemkhar_Manam"],
    "Yalang": ["Dhoogti_Gashing", "Chhema_Melongkhar", "Namthig_Yerphel", "Rolam_Thragom", "Phuyang_Yalang"],
  },
  "Trongsa": {
    "Draagteng": ["Tagtse_Tashidingkha", "Uesar", "Kuenga Rabten", "Samling Khatoed", "Samling Khamaed"],
    "Korphu": ["Nabi", "Korphu Maed", "Korphu Toed", "Nyimzhong Toed", "Nyimzhong Maed"],
    "Langthil": ["Langthil", "Yuedroongchhoeling", "Jangbi", "Dhangdoong", "Baling"],
    "Nubi": ["Gagar_Kar-Zhong", "Dharbab_Sinphu", "Bemji_Chela", "Bji_Saengmbji", "Baagochen _Boolingpang_Ueling"],
    "Tangsibji": ["Chendenbji", "Nyala Drangla", "Tangsibji", "Tshangkha", "Kela"],
  },
  "Tsirang": {
    "Barshong": ["Barshong Maed", "Barshong Toed", "Choonyikhang", "Gangtogkha", "Toedsang"],
    "Patshaling": ["Thakorling", "Chhudzomsa", "Patshaling Toed", "Patshaling Maed_Tsakaling", "Pangthang"],
    "Kilkhorthang": ["Dekiling", "Tashiyangjong", "Nyizergang", "Sa-Tsangma", "Maenchhana"],
    "Mendrelgang": ["Dzamling Zor", "Pemashong_Samshing Gaden", "Mendrelgang", "Riserbu", "Tashipang"],
    "Rangthangling": ["Soonkosh", "Gagaling_Nyimazor", "Charingma_Rangthangling", "Neymedsa"],
    "Tsholingkhar": ["Dharchhargang", "Gomsoom", "Tsholingkhar Maed", "Tsholingkhar Toed"],
    "Doonglagang": ["Droobchhugang", "Kapazhing", "Dangreybu Maed", "Dangreybu Toed", "Khirithang", "Dingrigang_Lhamoi-Loongm", "Norjangsa"],
    "Gosarling": ["Phuensoomgang", "Dzamling Zor", "Pemathang", "Pelrithang", "Dzamlingthang"],
    "Sergithang": ["Norboogang", "Sergithang Toed", "Sergithang Maed", "Tashithang", "Semdenjong"],
    "Pungtenchhu": ["Norbuthang", "Tashichhoeling", "Peljorling", "Goentegkha_Tongshinggang", "Serzhong"],
    "Semjong": ["Dekiling", "Dangreygang", "Dzomling", "Tashiling Maed", "Tashiling Toed"],
    "Tsirang Toed": ["Tagthang_Wangphu", "Kabelzhing", "Tsirang Toed", "Tongshingnang", "Soentabsa"],
  },
  "Wangdue Phodrang": {
    "Athang": ["Jaroggang_Dzawo", "Lomtshokha", "Lophokha_Phagtakha", "Lawa_Lamga", "Rookha"],
    "Bjednag": ["Bjednagloongpa_Thingmakha", "Tashi Tokha", "Wachhey", "Garzhikha_Omchheygang", "Ngawang_Tongchennang"],
    "Darkar": ["Uma Khatoed", "Kameychhu_Uma Khamaed", "Kamina_Wogyal", "Gyapakha", "Sili_Taagsha"],
    "Gase Tshogongm": ["Changche_Matshigpogto", "Khamaedna", "Khatoedkha", "Changkha", "Dabchhaykha_Matshigkha"],
    "Gase Tshowogm": ["Haetshokha", "Shingkhey_Khatoed", "Shingkhey_Khamaed", "Medpaisa_Taabchhaekha", "Haebisa"],
    "Nahi": ["Khoorjoongla_Langmizi", "Haebisa", "Uesagongm_Thabji", "Halued_Uesawogm", "Nagbisa"],
    "Thedtsho": ["Thanggoo", "Martaloongchu", "Wangjokha", "Rinchhengang Toed", "Rinchhengang Maed"],
    "Ruebisa": ["Bangtoedkha", "Bjagphu", "Khothangkha", "Gyala", "Oola", "Zamding"],
    "Dangchhu": ["Tashidingkha_Zimi", "Godraang_Taagsar", "Tokaling_Tomla", "DoongdoongNyelsa_Norbooding", "Uesagang"],
    "Gangteng": ["Jangchen_Koombu", "Gangteng", "Yaekorwog", "Tapaiteng_Uesa"],
    "Kazhi": ["Gorgoen", "Baedrog", "Lengbi"],
    "Nyishog": ["Chegidp", "Komathrang", "Kazhi", "Goensar_Radzawog", "Chitokha_Pangkha", "Gangjab", "Samtengang", "Geylegkha_Kuenzangling", "Chhaebhakha"],
    "Phangyuel": ["Uesargang _ Hampoekha", "Chhungserkha_Dhomkha", "Chhunggoen", "Goenkhar", "Koomchhi_Phangyuel"],
    "Phobji": ["Dogsenang_Gorphu", "Drangpa_Pangsar", "Khyimdro_Nemphel", "Talachen_Tawa_Ta-Phu", "Damchhoe_Gangphel"],
    "Saephu": ["Booso_Zeri", "Longtoed", "Boomilog", "Nakha", "Rukoobji"],
  },
  "Zhemgang": {
    "Bardo": ["Bardo", "Khomshar", "Phulabi", "Langdhorbi", "Dhigala"],
    "Nangkor": ["Dhakphel_Tali", "Buli", "Goleng", "Nyakhar", "Duenmang"],
    "Shingkhar": ["Radhi", "Shingkhar", "Wamling", "Thrisa", "Nyimzhong_Thajong"],
    "Trong": ["Berti_Tagma", "Dhangkhar_Trong", "Tshanglajong_Zurphel", "Soobdrang", "Gongphu"],
    "Bjoka": ["Dhali", "Bjoka", "Kamati", "Barpong_Namirgang"],
    "Goshing": ["Chabdenba_Zarkabla", "Mewanggang", "Budhashi"],
    "Ngangla": ["Lamthang", "Lingmapong_Samchhoeling", "Lichibi", "Kagtong", "Ngangla Trong", "Ribati", "Marangduet", "Panbang_Sonamthang"],
    "Phangkhar": ["Pongchola_Taduejong", "Mamo Trong_Pantang", "Panabi", "Shalingtoed_Tashibi", "Chag-Ngar-Zam"],
  },
};

export const DZONGKHAG_LIST = Object.keys(BHUTAN_ADMIN);
export function gewogsOf(dz: string): string[] {
  return dz && BHUTAN_ADMIN[dz] ? Object.keys(BHUTAN_ADMIN[dz]) : [];
}
export function chiwogsOf(dz: string, gw: string): string[] {
  return dz && gw && BHUTAN_ADMIN[dz]?.[gw] ? BHUTAN_ADMIN[dz][gw] : [];
}